server:
  port: 8081

my:
  greeting: "Welcome to my Application"
  dbValues: "Demo Db values from prop file"
  list:
    values: One, Two, Three

db:
  connection: "url = localhost:8080/ajith, userName = Ajith, password = pass"
  host: 127.0.0.1
  port: 600


